flags: {}
packages:
- '.'
- location:
    git: git@github.com:Gabriel439/Haskell-Morte-Library.git
    commit: 845bf236e817d7cd14e9b5c6081df2a5efadcac2
- location:
    git: git@github.com:int-index/source.git
    commit: e7c3cc4b26a27497046b2a93081bc3a510e52c77
  subdirs:
    - lib
extra-deps: []
resolver: lts-3.1
