flags: {}
packages:
- '.'
- location:
    git: https://github.com/int-index/Haskell-Morte-Library
    commit: 6941b841129c79ac64e25917ca5b0c41ba3e01c7
- location:
    git: https://github.com/int-index/source
    commit: 79b35d6f6dda5e936929d54c48812764252128b1
  subdirs:
    - lib
resolver: lts-3.16
