flags: {}
packages:
- '.'
- location:
    git: git@github.com:int-index/source.git
    commit: 6d3c70dae2d0deef0060a26297f93bfce025227d
  subdirs:
    - lib
extra-deps:
- singletons-2.0.0.2
- morte-1.3.1
resolver: lts-3.9
