flags: {}
packages:
- '.'
- location:
    git: git@github.com:Gabriel439/Haskell-Morte-Library.git
    commit: 845bf236e817d7cd14e9b5c6081df2a5efadcac2
- location:
    git: git@github.com:int-index/source.git
    commit: 25c530b45fe9c75dbbf30a707e66d6a94866dd73
  subdirs:
    - lib
extra-deps: []
resolver: lts-3.1
