flags: {}
packages:
- '.'
- location:
    git: git@github.com:Gabriel439/Haskell-Morte-Library.git
    commit: 845bf236e817d7cd14e9b5c6081df2a5efadcac2
- location:
    git: git@github.com:int-index/source.git
    commit: f42916fb54d77be2b2614cae762b7db3fbc21046
  subdirs:
    - lib
extra-deps: []
resolver: lts-3.1
