flags: {}
packages:
- '.'
- location:
    git: https://github.com/int-index/source
    commit: c8062c86618b358dc15cc21c807dde131029a1a7
  subdirs:
    - lib
extra-deps:
- singletons-2.0.0.2
- morte-1.3.1
resolver: lts-3.10
