flags: {}
packages:
- '.'
- location:
    git: git@github.com:Gabriel439/Haskell-Morte-Library.git
    commit: 845bf236e817d7cd14e9b5c6081df2a5efadcac2
- location:
    git: git@github.com:int-index/source.git
    commit: aebdbab4fd71aba33c18c4d4ad9b25c7245b7106
  subdirs:
    - lib
extra-deps: []
resolver: lts-3.1
