flags: {}
packages:
- '.'
- location:
    git: https://github.com/int-index/source
    commit: a3bfd6927b7010dab50c66adba6b64bd6acaef03
  subdirs:
    - lib
resolver: nightly-2015-11-23
extra-deps: []
