flags: {}
packages:
- '.'
- location:
    git: git@github.com:Gabriel439/Haskell-Morte-Library.git
    commit: 845bf236e817d7cd14e9b5c6081df2a5efadcac2
- location:
    git: git@github.com:int-index/source.git
    commit: 2dc9dc03009a27fd5d8b1a179a4364ac30c09422
  subdirs:
    - lib
extra-deps: []
resolver: lts-3.1
